language: generic
services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=opp.rosinstall
    - ROS_REPO=ros
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"
    - ROSDEP_SKIP_KEYS="libqt5sql5-mysql"

jobs:
  include:
    - os: linux
      dist: bionic
      language: cpp
      env:
      - ROS_DISTRO="melodic"
      - CLANG_FORMAT_CHECK=file
      - CLANG_FORMAT_VERSION=8
      - AFTER_SCRIPT=""
      - BADGE=clang-format
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: xenial
      language: cpp
      env:
      - ROS_DISTRO="kinetic"
      - DOCKER_IMAGE=rosindustrial/noether:kinetic
      - NOT_TEST_BUILD=true
      - BEFORE_INIT="apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"
      - BADGE=xenial
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: bionic
      language: cpp
      env:
      - ROS_DISTRO="melodic"
      - NOT_TEST_BUILD=true
      - ADDITIONAL_DEBS=libvtk7-dev libqt5sql5-mysql
      - BEFORE_INIT="apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"
      - BADGE=melodic
      cache:
        directories:
          - $HOME/.ccache

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - .industrial_ci/travis.sh
